name: graduation_project
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter




  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.5
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.5
  get: ^4.6.5
  get_it: ^7.6.0
  shared_preferences: ^2.2.0
  font_awesome_flutter: ^10.5.0
  flutter_state_render_dialog: ^1.0.4
  flutter_facebook_auth: ^3.5.3
  flutter_secure_storage: ^8.0.0
  intl: ^0.17.0
  image_picker: ^1.0.2
  image_cropper: ^5.0.0
  hive: ^2.2.3
  path_provider: ^2.1.0
  hive_flutter: ^1.1.0
  uuid: ^3.0.7
  animated_bottom_navigation_bar: ^1.2.0
  flutter_snake_navigationbar: ^0.6.1
  flutter_advanced_drawer: ^1.3.5
  flutter_slider_drawer: ^2.1.3
  awesome_drawer_bar: ^1.2.0
  hidden_drawer_menu: ^3.0.1
  loading_animation_widget: ^1.2.0+4

#  google_sign_in: '^4.5.1'


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
