// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz8w6UjOxk2ytJuwo-D-w0FyVeqIXHdEI',
    appId: '1:28368143613:web:67b34c3cc3e8f2bb636a94',
    messagingSenderId: '28368143613',
    projectId: 'jobsapp-46310',
    authDomain: 'jobsapp-46310.firebaseapp.com',
    storageBucket: 'jobsapp-46310.appspot.com',
    measurementId: 'G-W7ZKE2X1TE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIHll-c4r75pHig8mYVOf7yrw-B0dYdxw',
    appId: '1:28368143613:android:aaab33ba93f789bf636a94',
    messagingSenderId: '28368143613',
    projectId: 'jobsapp-46310',
    storageBucket: 'jobsapp-46310.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJk_IktR11kUYpijP8Tq-hCnZ4Ihnk7ec',
    appId: '1:28368143613:ios:7a877bc668392c2f636a94',
    messagingSenderId: '28368143613',
    projectId: 'jobsapp-46310',
    storageBucket: 'jobsapp-46310.appspot.com',
    iosClientId: '28368143613-1r1ckntvcsbviqql9319ad5014efkdhu.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJk_IktR11kUYpijP8Tq-hCnZ4Ihnk7ec',
    appId: '1:28368143613:ios:b7f19455695024e3636a94',
    messagingSenderId: '28368143613',
    projectId: 'jobsapp-46310',
    storageBucket: 'jobsapp-46310.appspot.com',
    iosClientId: '28368143613-7ti8atkiovf73n728836nnm77qioosak.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduationProject.RunnerTests',
  );
}
